"""add last_checked_at to monitors

Revision ID: 78958a6683e8
Revises: 02806dd6f9a6
Create Date: 2026-09-15 20:57:52.864804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78958a6683e8'
down_revision: Union[str, Sequence[str], None] = '02806dd6f9a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitors',
                sa.Column('last_checked_at', sa.DateTime(),
                        nullable=True,)
                        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitors', 'last_checked_at')
    # ### end Alembic commands ###
