"""use timezone aware timestamps

Revision ID: 8f2e1b9b4be9
Revises: 78958a6683e8
Create Date: 2026-09-20 20:31:42.180283

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8f2e1b9b4be9"
down_revision: Union[str, Sequence[str], None] = "78958a6683e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "checks",
        "checked_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        postgresql_using="checked_at AT TIME ZONE 'Asia/Yekaterinburg'",
    )
    op.alter_column(
        "monitors",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        postgresql_using="created_at AT TIME ZONE 'Asia/Yekaterinburg'",
    )
    op.alter_column(
        "monitors",
        "last_checked_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        postgresql_using="last_checked_at AT TIME ZONE 'Asia/Yekaterinburg'",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "monitors",
        "last_checked_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        postgresql_using="last_checked_at AT TIME ZONE 'Asia/Yekaterinburg'",
    )
    op.alter_column(
        "monitors",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        postgresql_using="created_at AT TIME ZONE 'Asia/Yekaterinburg'",
    )
    op.alter_column(
        "checks",
        "checked_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        postgresql_using="checked_at AT TIME ZONE 'Asia/Yekaterinburg'",
    )
    # ### end Alembic commands ###
